#ifndef _CONSTANTE_H_
#define _CONSTANTE_H_

#define PT_VIE_UNITE_1 50
#define PT_ATTAQUE_UNITE_1 10
#define PT_ACTION_UNITE_1 10
#define PT_DEPLACEMENT_UNITE_1 10
#define PT_MOUVEMENT_UNITE_1 10
#define NB_TOUR_UNITE_1 1
#define NB_METAL_UNITE_1 100


#endif
